---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: duplicate-ingress-check
  namespace: kuberhealthy
spec:
  runInterval: 5m
  timeout: 15m
  podSpec:
    securityContext:
      runAsUser: 999
      fsGroup: 999
    containers:
      - env:
        - name: REPORT_FAILURE
          value: "false"
        - name: REPORT_DELAY
          value: "5s"
        image: pasientskyhosting/kuberhealthy-duplicate-ingress-check:v1.0.0
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
    serviceAccountName: duplicate-ingress-check-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: duplicate-ingress-check-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: duplicate-ingress-check-role
subjects:
  - kind: ServiceAccount
    name: duplicate-ingress-check-sa
    namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: duplicate-ingress-check-role
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: duplicate-ingress-check-sa
  namespace: kuberhealthy
