name: Sync to ReadMe
on:
  push:
    branches:
      - master
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - uses: pasientskyhosting/github-actions/github-readme-md-sync@master
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}' # DON'T MODIFY--Allows us to get the contents of your repo
          file-path: '' # path to markdown files
          readme-api-key: '${{ secrets.README_API_KEY }}' # ReadMe API key 
          readme-api-version: '1.0' # ReadMe version to sync to
